### ISSUE TITLE
Create Doc for Process

### ISSUE THREAD

**Issue by Yogeshtake2** [taketwotech/docs-proctoring#1]
create a doc which is understandable to whole team members about the issue tracking process

**Comment by PriyankaTake2** [comment]
@Yogeshtake2  I have reviewed the doc.

This doc is clear and detailed, however text heavy! Screenshots needs to be added to make it easier for everyone to follow. 

Each repository should be defined separately with their links and screenshots - we need to use 3 for this project - one for Moodle Plugin, one for Python APIs, and one for dashboard.

Along with this documentation, we need to set up a meeting with the team members to guide them through this process. This document can work as a supplement which they can refer anytime.

**Comment by Yogeshtake2** [comment]
i have added more useful info and screenshots. if the doc is clear and understandable then please resolve your comments and close this issue @PriyankaTake2

**Comment by PriyankaTake2** [comment]
@Yogeshtake2 - I feel we should clearly mention about the 3 important labels - lms plugin, rtc (node app), and proctor (Python API) in the doc. Explain the difference between all 3 and their categorization.

**Comment by Yogeshtake2** [comment]
@PriyankaTake2 done, please check the doc.

**Comment by PriyankaTake2** [comment]
@Yogeshtake2 Looks good to me! Closing this issue. Please ensure to have a call with the team members to communicate this process and share this doc with them.
