### ISSUE TITLE
Create a Doc with Structure for Technical KB

### ISSUE THREAD

**Issue by Yogeshtake2** [taketwotech/docs-proctoring#6]
Proctoring Tool documentation structure for technical team.

**Comment by PriyankaTake2** [comment]
First draft_v0.1 - https://docs.google.com/document/d/1kBW86PNBOi34ixYRF-9UfXyblg4ysQLdIotTVRKzVKA/edit?usp=sharing

Please suggest any changes and modifications. @Yogeshtake2 @msoni11

**Comment by PriyankaTake2** [comment]
@msoni11 suggested: 
Code base is not required as we already have it on GitHub. 
We can add repo link there.

No other feedback received on this doc. Closing this issue.
