### ISSUE TITLE
Create Doc for Ruchi's Technical Questions

### ISSUE THREAD

**Issue by PriyankaTake2** [taketwotech/docs-proctoring#7]
Add screenshots/links and relevant info to the questions as requested by Ruchi.

**Comment by Yogeshtake2** [comment]
https://docs.google.com/document/d/1eGnlHpDADZVBotC1tf5qL2l1Lpx6BsMlbDQ3CQirTL0/edit

**Comment by PriyankaTake2** [comment]
@Yogeshtake2 Please update here when Ruchi's comment is resolved.

**Comment by Yogeshtake2** [comment]
@PriyankaTake2 all comments are resolved.
